### Write ci yaml here
name: CI
 
on:
    push:
        branches: ["develop"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
