### Write ci yaml here
name: CI
 
on:
    push:
        branches: ["develop"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:   
            - uses: actions/checkout@v2
            
            - name: Install node 
              uses: actions/setup-node@v3
            - run: npm install
            - run: npm run build --prod
            #- run: npm test

    # Image_Create:
    #     needs: build
    #     runs-on: ubuntu-latest

            - name: Build Docker Image
              uses: mr-smithers-excellent/docker-build-push@v3
              with: 
                image: chaudhariraj/angular-hw
                tag: github
                registry: docker.io
                dockerfile: Dockerfile 
                username: chaudhariraj
                password: Craj@2026%